routes/web.php
<?php
//Auth::routes();

// Authentication Routes...
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');
Route::get('logout', 'Auth\LoginController@logout')->name('logout');
// Route::get('logout', function(){
//   echo 'Boo';
// });

// Registration Routes...
// Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
// Route::post('register', 'Auth\RegisterController@register');

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');

// Posts
// Route::get('/projects', 'PostsController@index')->name('projects');
//
// Route::get('/posts/create', 'PostsController@create');
//
// Route::post('/posts', 'PostsController@store');
//
// Route::get('/posts/{post}', 'PostsController@show');
//
// Route::get('posts/{id}/edit', 'PostsController@edit');
//


Route::resource('posts', 'PostsController');
//Route::get('/projects', 'PostsController@index')->name('projects');
Route::view('/freelancer', 'static.freelancer');

Route::get('/',['as'=>'home', function(){
  return view('static.freelancer');
}]);

Route::get('contact',
  ['as' => 'contact', 'uses' => 'ContactController@create']);
Route::post('contact',
  ['as' => 'contact_store', 'uses' => 'ContactController@store']);

Route::get('/posts/tags/{tag}', 'TagsController@show');

// Route::get('/freelancer', function(){
// return 'Hello World';
// });

// Route::get('/experience',['as'=>'experience', function(){
//   return view('static.experience');
// }]);

resources/views/layouts/_flash.blade.php
   @if (Session::has('flash_message'))
            <div class="alert alert-success" {{ Session::has('flash_message_important') ? 'alert-important' : '' }}>
                 @if(Session::has('flash_message_important'))
                 <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                @endif
                {{ session('flash_message') }}
            </div>
   @endif<?php

resources/views/layouts/errors.blade.php
    
@if(count($errors))
<div class="form-group">

    <div class="alert alert-danger">
        <ul>

            @foreach($errors->all() as $error)

            <li>{{ $error }}</li>

            @endforeach

        </ul>
    </div>
</div>
@endif

resources/views/layouts/footer.blade.php
<!-- Bootstrap core JavaScript -->
<script src="/vendor/jquery/jquery.min.js"></script>
<script src="/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

<!-- Plugin JavaScript -->
<script src="/vendor/jquery-easing/jquery.easing.min.js"></script>

<!-- Custom scripts for this template -->
<script src="/js/resume.min.js"></script>
<script src="/vendor/ckeditor/ckeditor.js"></script>
<script>
    // Replace the <textarea id="editor1"> with a CKEditor
    // instance, using default configuration.
    CKEDITOR.replace( 'body' );
</script>

resources/views/layouts/master.blade.php
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Freelance PHP Developer</title>

    <!-- Bootstrap core CSS -->
    <link href="/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="https://fonts.googleapis.com/css?family=Saira+Extra+Condensed:100,200,300,400,500,600,700,800,900" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i" rel="stylesheet">
    <link href="/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <link href="/vendor/devicons/css/devicons.min.css" rel="stylesheet">
    <link href="/vendor/simple-line-icons/css/simple-line-icons.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/css/resume.min.css" rel="stylesheet">

  </head>

  <body id="page-top">

    @include('layouts.nav')

    @yield('content')

    @include('layouts.footer')

  </body>

</html>

resources/views/layouts/nav.blade.php
<nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top" id="sideNav">
  <a class="navbar-brand js-scroll-trigger" href="#page-top">
    <span class="d-block d-lg-none">Start Bootstrap</span>
    <span class="d-none d-lg-block">
      <img class="img-fluid img-profile rounded-circle mx-auto mb-2" src="/img/profile.png" alt="">
    </span>
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link js-scroll-trigger" href="/#about">About</a>
      </li>
      <li class="nav-item">
        <a class="nav-link js-scroll-trigger" href="/#services">Services</a>
      </li>
      <li class="nav-item">
        <a class="nav-link js-scroll-trigger" href="/#skills">Skills</a>
      </li>
      <li class="nav-item">
        <a class="nav-link js-scroll-trigger" href="{{ route('posts.index') }}">Portfolio</a>
      </li>
      <li class="nav-item">
        <a class="nav-link js-scroll-trigger" href="{{ route('contact') }}">Contact</a>
      </li>
    </ul>
  </div>
</nav>

resources/views/layouts/sidebar.blade.php
<aside class="col-sm-3 ml-sm-auto blog-sidebar">
  <!-- <div class="sidebar-module sidebar-module-inset">
      <h4>About</h4>
      <p>Some <em>stuff</em>.</p>
  </div> -->
  <div class="sidebar-module">
      <h4>Archives</h4>
      <ol class="list-unstyled">

          @foreach ($archives as $archive)
              <li>

                  <a href="{{ route('posts.index') }}/?month={{ $archive['month']}}&year={{$archive['year']}}">
                      {{ $archive['month'] . ' ' . $archive['year'] }}
                  </a>

              </li>
          @endforeach

      </ol>
  </div>
      <div class="sidebar-module">
      <h4>Tags</h4>
      <ol class="list-unstyled">

          @foreach ($tags as $tag)
              <li>

                  <a href="/posts/tags/{{ $tag }}">
                      {{ $tag }}
                  </a>

              </li>
          @endforeach

      </ol>
  </div>
  <div class="sidebar-module">
      <h4>Elsewhere</h4>
      <ol class="list-unstyled">
          <li><a href="https://bitbucket.org/account/signin/">Bitbucket</a></li>
          <li><a href="https://twitter.com/mgiambro">Twitter</a></li>
      </ol>
  </div>
</aside><!-- /.blog-sidebar -->